### PR TITLE
initial SysTray PR

### PR DESCRIPTION
**Pull request by conlan0**
- This is windows support only
- Added system tray icon with support for a menu with links and dividers and the support for submenus with links
- Agent gets a nats signal every 5 mins to restart and update systray icon, name and config
- Agent runs the systray on startup

### CODE REVIEW

**Review by wh1te909 — COMMENTED** [review]
To fix the failing tests we need to ensure the windows only stuff lives in files named `something_windows.go` and then stub the functions for linux/mac. You can stub them in `agent_unix.go`

**Comment by conlan0** [comment]
> To fix the failing tests we need to ensure the windows only stuff lives in files named `something_windows.go` and then stub the functions for linux/mac. You can stub them in `agent_unix.go`

got that done but i think theirs an issue where i import support in main.go here 

	'case "tray":

		if runtime.GOOS == "windows" {
			support.InitTrayIcon()
		}`

**Comment by wh1te909** [comment]
I don't see any stubs. Look at https://github.com/amidaware/rmmagent/blob/b09eaf84de68dfb4f3cb6db6ff364a6745efd943/agent/agent_unix.go#L903 and you'll need to stub all the new systray related windows

**Comment by conlan0** [comment]
okay got it. how do i update its packages now?

**Comment by wh1te909** [comment]
You need to also add your `go.mod` and `go.sum` changes, I don't see those updated. When you installed that systray package on your local machine it would have updated these 2 files.

**Comment by conlan0** [comment]
now its getting the download errors i do lol

**Review by wh1te909 — CHANGES_REQUESTED** [review]

**Pull request closed without merging**
